<link rel="stylesheet" href="<?= H(RURL('gapper-client-nk.css', 'css')) ?>" type="text/css" charset="utf-8">
<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('绑定账号'))?></h4>
            </div>
            <form class="modal-body form gapper-auth-form" method="POST" action="ajax/gapper/auth/nk/active"><dl class="dl-horizontal">
                <input type="hidden" name="username" value="<?=H($username)?>" />
                <input type="hidden" name="password" value="<?=H($password)?>" />
                <dt class="text-center">
                    <div class="app-icon">
                        <div class="text-center app-icon-image"><img src="<?=H($icon)?>" /></div>
                        <div class="text-center app-icon-title"><?=H($type)?></div>
                    </div>
                </dt>
                <dd class="gapper-auth-nk-form-active">
                    <h4><?=H(T('您的账号是初次登录, 请您补全相关信息:'))?></h4>

                    <div>
                        <?php if ($error['name']) { ?>
                        <div class="text-right gapper-auth-nk-form-active-e"><small><?=H($error['name'])?></small></div>
                        <?php }?>
                        <div style="display:none; display/*\**/:block\9;"><?=H(T('姓名:'))?></div>
                    </div>
                    <div class="gapper-auth-nk-form-active-li<?=$error['name'] ? ' has-error' : ''?>">
                        <input class="form-control" type="text" name="name" value="<?=H($name)?>" placeholder="<?=H(T('姓名'))?>" />
                    </div>

                    <div>
                        <?php if ($error['email']) { ?>
                        <div class="text-right gapper-auth-nk-form-active-e"><small><?=H($error['email'])?></small></div>
                        <?php }?>
                        <div style="display:none; display/*\**/:block\9;"><?=H(T('Email:'))?></div>
                    </div>
                    <div class="gapper-auth-nk-form-active-li<?=$error['email'] ? ' has-error' : ''?>">
                        <input class="form-control" type="text" name="email" value="<?=H($email)?>" placeholder="<?=H(T('Email'))?>" />
                    </div>
                    <div class="text-right gapper-auth-nk-form-active-s"><small><?=H(T('请是用正确的Email, 该Email已经注册不允许更改!'))?></small></div>

                    <div>
                        <?php if ($error['group']) { ?>
                        <div class="text-right gapper-auth-nk-form-active-e"><small><?=H($error['group'])?></small></div>
                        <?php }?>
                        <div style="display:none; display/*\**/:block\9;"><?=H(T('组标识:'))?></div>
                    </div>
                    <div class="gapper-auth-nk-form-active-li<?=$error['group'] ? ' has-error' : ''?>">
                        <input class="form-control" type="text" name="group" value="<?=H($group)?>" placeholder="<?=H(T('组标识'))?>" />
                    </div>

                    <div>
                        <?php if ($error['title']) { ?>
                        <div class="text-right gapper-auth-nk-form-active-e"><small><?=H($error['title'])?></small></div>
                        <?php }?>
                        <div style="display:none; display/*\**/:block\9;"><?=H(T('组名:'))?></div>
                    </div>
                    <div class="gapper-auth-nk-form-active-li<?=$error['title'] ? ' has-error' : ''?>">
                        <input class="form-control" type="text" name="title" value="<?=H($title)?>" placeholder="<?=H(T('组名'))?>" />
                    </div>

                    <div class="form-group">
                        <input class="form-control btn btn-primary" type="submit" value="<?=H(T('提交'))?>"/>
                    </div>
                </dd>
            </dl></form>
        </div>
    </div>
</div>
