---
backends:
  ids.nankai.edu.cn:
    title: 一卡通用户
    driver: ldap
    ldap.username_base: dc=nankai,dc=edu,dc=cn
    ldap.username_attr: uid
    ldap.options:
      server_type: ads
      host: IDSHOST             # ldap://DOMAIN
      root_dn: IDS_ROOTDN
      root_pass: IDS_ROOTPASS
      pass_algo: IDS_ALGO
...
